### ISSUE TITLE
Unable to load plugin. No plugin.yml

### ISSUE THREAD

**Issue by TheShinPin** [henkelmax/audio-player#1]
[05:01:32] [Server thread/ERROR]: Could not load 'plugins/audioplayer-1.18.2-1.0.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:406) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3468-Spigot-ffceeae-d53c4fb]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:232) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3468-Spigot-ffceeae-d53c4fb]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3468-Spigot-ffceeae-d53c4fb]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3468-Spigot-ffceeae-d53c4fb]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 7 more

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/160985881-34186c67-e13d-460f-8836-831dc9eee761.png)

**Comment by jle646YT** [comment]
I am not able to add the plugin. Plz help
![Screenshot (28)](https://user-images.githubusercontent.com/110491023/182448282-f85ee56c-1f0b-4b51-88af-30ba397734a8.png)
