### ISSUE TITLE
Error converting mp3 file with native decoder

### ISSUE THREAD

**Issue by Pitrex111** [henkelmax/audio-player#69]
Error happened when trying to play DeckedOut 2 on Hermitcraft map. When custom tracks are run following error is raised in console:
`[12:09:08] [AudioPlayerThread/ERROR]: [voicechat] Failed to load mp3 decoder
de.maxhenkel.lame4j.UnknownPlatformException: Could not load lame4j natives for linux-x64
	at de.maxhenkel.lame4j.LibraryLoader.load(LibraryLoader.java:122) ~[voicechat-fabric-1.20.1-2.4.25.jar:?]
	at de.maxhenkel.lame4j.Lame.load(Lame.java:23) ~[voicechat-fabric-1.20.1-2.4.25.jar:?]
	at de.maxhenkel.lame4j.Mp3Decoder.<init>(Mp3Decoder.java:14) ~[voicechat-fabric-1.20.1-2.4.25.jar:?]
	at de.maxhenkel.voicechat.plugins.impl.mp3.Mp3DecoderImpl.<init>(Mp3DecoderImpl.java:25) ~[voicechat-fabric-1.20.1-2.4.25.jar:?]
	at de.maxhenkel.voicechat.plugins.impl.mp3.Mp3DecoderImpl.lambda$createDecoder$0(Mp3DecoderImpl.java:74) ~[voicechat-fabric-1.20.1-2.4.25.jar:?]
	at de.maxhenkel.voicechat.voice.common.Utils.lambda$createSafe$1(Utils.java:251) ~[voicechat-fabric-1.20.1-2.4.25.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.UnsatisfiedLinkError: /tmp/lame4j-c4c91cffccdccba5ddf7844d59c09d4c/liblame4j.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/lame4j-c4c91cffccdccba5ddf7844d59c09d4c/liblame4j.so)
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at de.maxhenkel.lame4j.LibraryLoader.load(LibraryLoader.java:120) ~[voicechat-fabric-1.20.1-2.4.25.jar:?]
	... 6 more
[12:09:08] [AudioPlayerThread/WARN]: Error converting mp3 file with native decoder`

Mods Loaded:
audioplayer-1.20.1-1.7.1
fabric-api-0.83.0+1.20
fabric-carpet-1.20-1.4.112+v230608
voicechat-fabric-1.20.1-2.4.25

**Comment by henkelmax** [comment]
Your OS is missing `GLIBC 2.29`

**Comment by Pitrex111** [comment]
Ok, nevermind had to install library separatelly. I guess I'm too new to linux
